version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/emeax:/usr/share/nginx/html/emeax
      - ./src/onomis:/usr/share/nginx/html/onomis
    depends_on:
      - onomis_react
      - onomis_vue
      - onomis_docs

  onomis_react:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.react
    ports:
      - "3000:3000"

  onomis_vue:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.vue
    ports:
      - "3001:3001"

  onomis_docs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.docs
    ports:
      - "3002:3002"
