version: '3'
services:
  nginx:
      build:
        context: .
        dockerfile: docker/Dockerfile.nginx
      ports:
        - "80:80"
      volumes:
        - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      environment:
        - SERVER_NAME=${SERVER_NAME}
      depends_on:
        - PLACEHOLDER_DEPENDS_ON_SERVICES
      networks:
        - frontend_network

  onomis-react:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.react
      args:
        FOLDER_NAME: onomis-react
        PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - frontend_network

  onomis-vue:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.vue
      args:
        FOLDER_NAME: onomis-vue
        PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - frontend_network

  onomis-docs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.docs
      args:
        FOLDER_NAME: onomis-docs
        PORT: 3001
    ports:
      - "3002:3002"
    networks:
      - frontend_network

  emeax:
    build:
      context: .
      dockerfile: docker/Dockerfile.javascript
      args:
        FOLDER_NAME: emeax
        PORT: 3003
    ports:
      - "3003:3003"
    networks:
      - frontend_network

  onomis:
    build:
      context: .
      dockerfile: docker/Dockerfile.javascript
      args:
        FOLDER_NAME: onomis
        PORT: 3004
    ports:
      - "3004:3004"
    networks:
      - frontend_network


networks:
  frontend_network:
    driver: bridge
