version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - onomis_react
      - onomis_vue
      - onomis_docs
      - emeax_landing
      - onomis_landing
    networks:
      - frontend_network

  onomis_react:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.react
      args:
        FOLDER_NAME: onomis-react
        PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - frontend_network

  onomis_vue:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.vue
      args:
        FOLDER_NAME: onomis-vue
        PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - frontend_network

  onomis_docs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.docs
      args:
        FOLDER_NAME: onomis-docs
        PORT: 3001
    ports:
      - "3002:3002"
    networks:
      - frontend_network

  emeax_landing:
    build:
      context: .
      dockerfile: docker/Dockerfile.javascript
      args:
        FOLDER_NAME: emeax
        PORT: 3003
    ports:
      - "3003:3003"
    networks:
      - frontend_network

  onomis_landing:
    build:
      context: .
      dockerfile: docker/Dockerfile.javascript
      args:
        FOLDER_NAME: onomis
        PORT: 3004
    ports:
      - "3004:3004"
    networks:
      - frontend_network


networks:
  frontend_network:
    driver: bridge
