events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name emeax.com www.emeax.com;

        # Proxy for Onomis React
        location /preview/onomis-react/ {
            proxy_pass http://onomis_react:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy for Onomis Vue
        location /preview/onomis-vue/ {
            proxy_pass http://onomis_vue:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy for Onomis Docs
        location /preview/onomis-docs/ {
            proxy_pass http://onomis_docs:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Serve Onomis Landing (HTML Project)
        location /onomis/ {
            proxy_pass http://onomis_landing:80;
        }

        # Serve Emeax Landing (HTML Project)
        location / {
            proxy_pass http://emeax_landing:80;
        }
    }
}
