events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name emeax.com www.emeax.com;

        location /preview/onomis-react/ {
            alias /usr/share/nginx/html/onomis-react/;
            try_files $uri /index.html;
        }

        location /preview/onomis-vue/ {
            alias /usr/share/nginx/html/onomis-vue/;
            try_files $uri /index.html;
        }

        location /preview/onomis-docs/ {
            alias /usr/share/nginx/html/onomis-docs/;
            try_files $uri /index.html;
        }

        location / {
            alias /usr/share/nginx/html/emeax/;
            try_files $uri /index.html =404;
        }
    }
}
