server {
    listen 80;
    server_name emeax.com www.emeax.com;

    # Onomis React
    location /preview/onomis-react/ {
        alias /usr/share/nginx/html/onomis-react/;
        index index.html;
        autoindex on;
    }

    # Onomis Vue
    location /preview/onomis-vue/ {
        alias /usr/share/nginx/html/onomis-vue/;
        index index.html;
        autoindex on;
    }

    # Onomis Docs
    location /preview/onomis-docs/ {
        alias /usr/share/nginx/html/onomis-docs/;
        index index.html;
        autoindex on;
    }

    # Onomis Landing (HTML Project)
    location /onomis/ {
        alias /usr/share/nginx/html/onomis/;
        index index.html;
        autoindex on;
    }

    # Emeax Landing (HTML Project)
    location / {
        alias /usr/share/nginx/html/emeax/;
        index index.html;
        autoindex on;
    }
}
