# Dockerfile for Onomis Docs Project
FROM node:16-alpine AS builder

WORKDIR /usr/src/app

# Install dependencies and build the project
COPY ./../src/onomis-docs/package*.json ./
RUN npm install
COPY ./../src/onomis-docs ./
RUN npm run docs:build

# Final stage: Copy build files to a dedicated directory in Nginx
FROM nginx:alpine
COPY --from=builder /usr/src/app/.vitepress/dist /usr/share/nginx/html/onomis-docs
