# Dockerfile for Onomis Docs Project

FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./../src/onomis-docs/package*.json ./

RUN npm install

COPY ./../src/onomis-docs/. ./

RUN npm run docs:build

RUN npm install -g serve

EXPOSE 3001

CMD ["serve", "-s", ".vitepress/dist"]
