# Dockerfile for React Project
FROM node:16-alpine

WORKDIR /usr/src/app

# Install dependencies and serve globally
COPY ./../src/onomis-react/package*.json ./
RUN npm install
RUN npm install -g serve

# Copy application source code
COPY ./../src/onomis-react/. ./

# Build the React project
RUN npm run build

# Expose port and start the server
EXPOSE 3000
CMD ["serve", "-s", "dist"]
