# Dockerfile for React Project
FROM node:16-alpine AS builder

WORKDIR /usr/src/app

COPY ./../src/onomis-react/package*.json ./
RUN npm install

COPY ./../src/onomis-react ./
RUN npm run build

# No final Nginx setup, just build and leave the output
